### ISSUE TITLE
Leaflet 1.0 support

### ISSUE THREAD

**Issue by Alexious-sh** [Zverik/Leaflet.LimitZoom#1]
Looks like Leaflet 1.0 has breaking changes, and this plugin stops working after update. Can it be adapted to support new version too?

**Comment by axeff** [comment]
~~I'm using the ContinuousZoom plugin with Leaflet 1.0.0-rc1 and there seem to be no issues~~

**Comment by Zverik** [comment]
When I adapt this plugin to 1.0, 0.7 would stop working, so I'm postponing this task until we get at least rc3 (not sure if this year).

**Comment by axeff** [comment]
I was wrong with my last comment. ContinousZoom doesn't work with 1.0.0-rc1

**Comment by dcohenb** [comment]
Any fix in sight for this? I need this plugin to work badly, been looking for this solution for 3 days now

**Comment by Zverik** [comment]
I have updated the plugins and the demo.
